name: "CI - Lint for Pull Requests"

on:
  pull_request:
    paths:
      - 'docs/**/*.md'
      - 'docs/**/*.mdx'
      - 'general/**/*.md'
      - 'general/**/*.mdx'
      - 'versioned_docs/**/*.md'
      - 'versioned_docs/**/*.mdx'
      - .markdownlint-cli2.cjs

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint markdown files
        run: yarn mdlint-all && yarn mdxlint-all

      - name: Check spelling
        run: yarn spell
