name: "CI - Push the list of migrated pages to WikiMedia"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        description: 'Set the debug mode'

jobs:
  run:
    # Only run on the canonical repository.
    if: github.repository == 'moodle/devdocs'

    name: Push migated pages to Wikimedia
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run update script
        run: yarn wikimedia-sync push-migrated
        env:
          DEBUG: ${{ github.event.inputs.debug }}
          WIKIMEDIA_DEBUG: ${{ github.event.inputs.debug }}
          WIKIMEDIA_SECRET: ${{ secrets.WIKIMEDIA_PASSWORD }}
          WIKIMEDIA_USER: ${{ secrets.WIKIMEDIA_USER }}
